#!/usr/bin/env bash
LC_ALL=C

local_branch=$(git symbolic-ref --short head)
echo "Running pre-commit hook on branch: $local_branch"
if [[ "$local_branch" == "main" ]]; then
    echo "Commit on main is now allowed. Please use a feature branch."
    exit 1
fi

valid_branch_regex="^(lab|project|assignment|homework|issue|feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-z0-9._-]+$"

message="ERROR on Commit. Branch name must adhere to this contract: $valid_branch_regex. Rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
