@startuml
scale 2
title "UML Class Diagram"
class Triangle {
    .. Instance Variables ..
    _side1: float
    _side2: float
    _side3: float
    .. Overloaded Methods ..
    + __init__(side1: float, side2: float, side3: float): None
    + __str__(): str
    + __repr__(): str
    .. Instance Methods ..
    + set_sides(side1: float, side2: float, side3: float): None
	+ sides(): Tuple[float, float, float]
    + perimeter(): float
    + area(): float
    + is_right_angled(): bool
}
@enduml
